// Interaction regression tests with a simulated DOM. Not visual/browser QA.
import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs';
import * as E from '../dist/engine.js';
const html=fs.readFileSync(new URL('../dist/index.html',import.meta.url),'utf8');
const source=fs.readFileSync(new URL('../dist/game.js',import.meta.url),'utf8').replace(/^import .*;\n/gm,'').replaceAll('import.meta.url',"'http://test/game.js'");
function setup(isMobile=true){
 const nodes=new Map(),all=[],events={};let document;
 class Element{constructor(attrs={}){this.attrs=attrs;this.id=attrs.id;this.dataset={};for(const[k,v]of Object.entries(attrs))if(k.startsWith('data-'))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,a)=>a.toUpperCase())]=v;this.style={};this.isConnected=true;this.hidden=false;this.open=false;const classes=new Set((attrs.class||'').split(' '));this.classList={add:(...a)=>a.forEach(v=>classes.add(v)),remove:(...a)=>a.forEach(v=>classes.delete(v)),contains:v=>classes.has(v),toggle:(v,b)=>{if(b===undefined)b=!classes.has(v);b?classes.add(v):classes.delete(v)}};all.push(this)}set innerHTML(v){this.html=v;register(v)}get innerHTML(){return this.html||''}setAttribute(k,v){this.attrs[k]=v}focus(){document.activeElement=this}querySelector(){return all.find(x=>x.dataset.action==='close-panels')}addEventListener(k,v){this[k]=v}showModal(){this.open=true}close(){this.open=false}}
 function register(s){for(const match of s.matchAll(/<[a-z][\w-]*\s+([^>]+)>/g)){const attrs={};for(const a of match[1].matchAll(/([\w-]+)="([^"]*)"/g))attrs[a[1]]=a[2];if(attrs.id&&nodes.has(attrs.id))continue;const n=new Element(attrs);if(attrs.id)nodes.set(attrs.id,n)}}
 register(html);
 document={body:new Element(),activeElement:null,hidden:false,getElementById:id=>nodes.get(id)||null,querySelectorAll:selector=>all.filter(n=>selector==='.panel'?n.classList.contains('panel'):selector==='.mobile-nav button'?n.id?.startsWith('nav-'):selector==='[data-category]'?'category'in n.dataset:selector.includes('aria-controls')?!!n.attrs['aria-controls']:false),addEventListener:(k,v)=>events[k]=v};
 class View{constructor(canvas,getState,getUI,tap){this.getState=getState;this.getUI=getUI;this.tap=tap}focus(){}zoomAt(){}}
 const context=vm.createContext({E,FactoryView:View,document,window:{addEventListener(){}},localStorage:{getItem:()=>null,setItem(){}},matchMedia:()=>({matches:isMobile,addEventListener(){}}),performance:{now:()=>0},setInterval:()=>0,setTimeout:()=>0,clearTimeout(){},Date,console,URL,Blob});
 vm.runInContext(source,context);return{nodes,document,run:code=>vm.runInContext(code,context)};
}
test('mobile construction previews a tile and spends gold only after confirmation',()=>{const {run,nodes}=setup();run('state.onboardDone=true');const gold=run('state.gold');run("chooseTool('dust');tap({x:3,y:8})");assert.equal(run('state.machines.length'),1);assert.equal(run('state.gold'),gold);assert.equal(nodes.get('confirm-placement').disabled,false);nodes.get('confirm-placement').onclick();assert.equal(run('state.machines.length'),2);assert.ok(run('state.gold')<gold);assert.equal(nodes.get('confirm-placement').disabled,true);run("tap({x:3,y:8})");nodes.get('confirm-placement').onclick();assert.equal(run('state.machines.length'),2);run('tap({x:9,y:9});cancel()');assert.equal(run('pendingPlacement'),null)});
test('selection keeps the map visible; settings and close remain explicit actions',()=>{const {run,nodes,document}=setup();run('tap({x:3,y:4})');assert.equal(document.body.dataset.mode,'selected');assert.equal(nodes.get('info-panel').classList.contains('open'),false);assert.equal(nodes.get('inspect-selection').hidden,false);nodes.get('inspect-selection').onclick();assert.equal(nodes.get('info-panel').classList.contains('open'),true);assert.equal(nodes.get('nav-info').attrs['aria-expanded'],'true');run('closePanels()');assert.equal(nodes.get('info-panel').classList.contains('open'),false);assert.equal(run('selected'),1)});
test('mobile relocation keeps contents and applies the preview orientation only on confirmation',()=>{const {run,nodes}=setup();run("state.onboardDone=true;state.machines.push(E.machine('chest',5,5,0,2));state.machines[1].buf.push({kind:'letter',text:'a'});tap({x:5,y:5});move();rotate();tap({x:6,y:5})");assert.equal(run('state.machines[1].x'),5);assert.equal(run('state.machines[1].dir'),0);nodes.get('confirm-placement').onclick();assert.equal(run('state.machines[1].x'),6);assert.equal(run('state.machines[1].dir'),1);assert.equal(run('state.machines[1].buf[0].text'),'a')});
test('desktop preserves direct placement and key dialogs render without interaction errors',()=>{const {run,nodes}=setup(false);run("state.onboardDone=true;chooseTool('dust');tap({x:3,y:8})");assert.equal(run('state.machines.length'),2);assert.equal(nodes.get('confirm-placement').hidden,true);for(const fn of ['showResearch','showStats','showRecord','showGoals','showMenu']){run(fn+'()');assert.equal(nodes.get('dialog').open,true)}});
test('catalog help opens each footprint diagram without selecting or buying a building',()=>{const {run,nodes}=setup();const gold=run('state.gold');for(const t of Object.keys(E.TYPES)){run(`showBuildingInfo('${t}')`);assert.equal(run('tool'),null);assert.equal(run('state.gold'),gold);assert.match(nodes.get('dialog-content').innerHTML,/building-diagram/)}run("showWord('chat')");assert.match(nodes.get('dialog-content').innerHTML,/Étudier ce mot/)});
test('multi-cell selection and blocked rotation preserve machine placement',()=>{const {run}=setup();run("state.machines=[];state.gold=10000;state.tier=7;const w=E.place(state,'word',8,8);E.place(state,'chest',8,9);tap({x:9,y:8})");assert.equal(run('selected'),run('state.machines[0].id'));run('rotate()');assert.equal(run('state.machines[0].dir'),0)});
