import test from 'node:test';
import assert from 'node:assert/strict';
import {FactoryView} from '../dist/world.js';
import {createState} from '../dist/engine.js';
const setup=(width=390,height=500)=>{const listeners={},element={textContent:''};globalThis.matchMedia=()=>({matches:true});globalThis.requestAnimationFrame=()=>{};globalThis.devicePixelRatio=2;globalThis.document={getElementById:()=>element,hidden:false};globalThis.ResizeObserver=class{constructor(cb){this.cb=cb}observe(){this.cb()}};const ctx=new Proxy({measureText:t=>({width:t.length*7})},{get:(t,k)=>t[k]||(()=>{}),set:(t,k,v)=>{t[k]=v;return true}});const canvas={getContext:()=>ctx,parentElement:{getBoundingClientRect:()=>({width,height})},getBoundingClientRect:()=>({left:0,top:0}),addEventListener:(k,fn)=>listeners[k]=fn,setPointerCapture(){}};const tapped=[],s=createState();const view=new FactoryView(canvas,()=>s,()=>({}),p=>tapped.push(p));return{view,canvas,listeners,tapped}};
const p=(id,x,y)=>({pointerId:id,clientX:x,clientY:y,button:0,preventDefault(){}});
test('canvas uses measured container, keeps 44px touch cells, and can render at requested widths',()=>{for(const [w,h]of [[320,568],[360,800],[390,844],[412,915],[768,1024],[844,390],[1024,768]]){const {view,canvas}=setup(w,h);assert.equal(view.width,w);assert.equal(canvas.width,w*2);view.zoomAt(.001);assert.ok(view.cell>=44);view.frame(1000);assert.ok(Number.isFinite(view.ox))}});
test('tap selects but pan and pointercancel never place an item',()=>{const {view,listeners:l,tapped}=setup();l.pointerdown(p(1,100,100));l.pointerup(p(1,100,100));assert.equal(tapped.length,1);const oldX=view.camera.x;l.pointerdown(p(2,100,100));l.pointermove(p(2,150,100));l.pointerup(p(2,150,100));assert.equal(tapped.length,1);assert.notEqual(view.camera.x,oldX);l.pointerdown(p(3,100,100));l.pointercancel(p(3,100,100));assert.equal(tapped.length,1)});
test('pinch zooms around fingers and releasing them causes no accidental construction',()=>{const {view,listeners:l,tapped}=setup();l.pointerdown(p(1,100,100));l.pointerdown(p(2,200,100));l.pointermove(p(2,250,100));assert.ok(view.zoom>1);l.pointerup(p(2,250,100));l.pointerup(p(1,100,100));assert.equal(tapped.length,0);assert.equal(view.pointers.size,0)});
